<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>x10</string>
	</array>
	<key>name</key>
	<string>X10</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(as|class|def|extends|haszero|implements|import|instanceof|interface|native|offers|package|struct|throws|operator)\b</string>
			<key>name</key>
			<string>storage.type.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abstract|extern|final|global|nonblocking|pinned|private|property|protected|public|safe|sequential|shared|static|transient|val|var)\b</string>
			<key>name</key>
			<string>storage.modifier.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.+?$</string>
			<key>name</key>
			<string>comment.line.double-slash.x10</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(assert|async|at|ateach|athome|atomic|break|case|catch|clocked|continue|default|do|else|finally|finish|for|if|in|next|offer|return|switch|throw|try|when|while)\b</string>
			<key>name</key>
			<string>keyword.control.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(new|super|this|self)\b</string>
			<key>name</key>
			<string>constant.language.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|null|true|here|void)\b</string>
			<key>name</key>
			<string>constant.language.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+|0[xX][0-9a-fA-F]+)[LlNn]?\b|\b(([0-9]+[Ee][-]?[0-9]+|([0-9]*\.[0-9]+|[0-9]+\.)([Ee][-]?[0-9]+)?)[fFdD]?|[0-9]+[FfDd])</string>
			<key>name</key>
			<string>constant.numeric.x10</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.x10</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.dougle.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|&amp;|&amp;&amp;|\||\|\||\*|%|\!</string>
			<key>name</key>
			<string>keyword.operator.x10</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.x10</string>
	<key>uuid</key>
	<string>98dfd6bf-d46a-4d8e-b681-fa11bb97c080</string>
</dict>
</plist>
